version: "3.8"

services:
  wvi-nginx:
    container_name: wvi-nginx
    build:
      context: .
      target: nginx-server
    ports:
      - "80:80"
    depends_on:
      - wvi-api
  wvi-api:
    container_name: wvi-api
    build:
      context: .
      target: flask-api
    volumes:
      - ~/.aws/:/root/.aws:ro
    ports:
      - "5000:5000"
    depends_on:
      - wvi-redis
  wvi-redis:
    container_name: wvi-redis
    image: "redis:alpine"